MinistryFunnel.FrontEnd/Models/LocationViewModel.cs
namespace MinistryFunnel.FrontEnd.Models
{
    public class LocationViewModel : BaseViewModel
    {
    }
}

MinistryFunnel.FrontEnd/Controllers/LocationController.cs
using Ganss.XSS;
using MinistryFunnel.FrontEnd.Helpers;
using MinistryFunnel.FrontEnd.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace MinistryFunnel.FrontEnd.Controllers
{
    [Authorize(Roles = "Database.Admin")]
    public class LocationController : BaseController
    {
        const string apiAction = "/api/location";

        // GET: Location
        public ActionResult Index()
        {
            var response = _apiHelper.Get(CompileUrl(apiAction), GetToken());

            if (response.IsSuccessful)
            {
                var locations = JsonConvert.DeserializeObject<IEnumerable<LocationViewModel>>(response.Content);
                return View(locations);
            }

            return View();
        }

        private string CompileUrl(string action)
        {
            return ConfigurationManager.AppSettings["ApiBaseUrl"] + action;
        }

        // GET: Location/Details/5
        public ActionResult Details(int id = -1)
        {
            var response = _apiHelper.Get(CompileUrl(apiAction), "id", id, GetToken());

            if (response.IsSuccessful)
            {
                var location = JsonConvert.DeserializeObject<LocationViewModel>(response.Content);
                return View(location);
            }

            TempData["MessageType"] = "Danger";
            TempData["Message"] = $"There was a problem finding this record. Please try again or contact your system administrator.";
            return View();
        }

        // GET: Location/Search/same
        public ActionResult Search(string searchText)
        {
            var sanitizer = new HtmlSanitizer();
            var sanitizedText = sanitizer.Sanitize(searchText);

            var response = _apiHelper.Get(CompileUrl(apiAction) + $"?searchText={sanitizedText}", GetToken());

            if (response.IsSuccessful)
            {
                var location = JsonConvert.DeserializeObject<IEnumerable<LocationViewModel>>(response.Content);
                return View("Index", location);
            }
            
            return View("Index");
        }

        // GET: Location/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Location/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                var json = new JavaScriptSerializer().Serialize(new LocationViewModel
                {
                    Name = Request.Form["Name"],
                    Archived = Request.Form["Archived"] == "true"
                });

                var response = _apiHelper.Post(CompileUrl(apiAction), json, GetToken());

                if (response.IsSuccessful)
                {
                    TempData["MessageType"] = "Success";
                    TempData["Message"] = $"Location, {Request.Form["Name"]}, Created";
                    return RedirectToAction("Index");
                }

                TempData["MessageType"] = "Danger";
                TempData["Message"] = $"There was a problem creating this record. Please try again or contact your system administrator.";
                return View();
            }
            catch
            {
                TempData["MessageType"] = "Danger";
                TempData["Message"] = $"There was a problem creating this record. Please try again or contact your system administrator.";
                return View();
            }
        }

        // GET: Location/Edit/5
        public ActionResult Edit(int id = -1)
        {
            var response = _apiHelper.Get(CompileUrl(apiAction), "id", id, GetToken());

            if (response.IsSuccessful)
            {
                var location = JsonConvert.DeserializeObject<LocationViewModel>(response.Content);
                return View(location);
            }

            TempData["MessageType"] = "Danger";
            TempData["Message"] = $"There was a problem retrieving this record. Please try again or contact your system administrator.";
            return View("Edit", null);
        }

        // POST: Location/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var updatedModel = new LocationViewModel
            {
                Id = id,
                Name = Request.Form["Name"],
                Archived = Request.Form["Archived"] == "true" 
            };

            try
            {
                var json = new JavaScriptSerializer().Serialize(updatedModel);
                var response = _apiHelper.Put(CompileUrl(apiAction) + $"?id={id}", json, GetToken());

                if (response.IsSuccessful)
                {
                    TempData["MessageType"] = "Info";
                    TempData["Message"] = $"Location, {Request.Form["Name"]}, Edited";
                    return RedirectToAction("Index", ViewBag);
                }

                TempData["MessageType"] = "Danger";
                TempData["Message"] = $"There was a problem updating this record. Please try again or contact your system administrator.";
                return View();
            }
            catch
            {
                TempData["MessageType"] = "Danger";
                TempData["Message"] = $"There was a problem updating this record. Please try again or contact your system administrator.";
                return View();
            }
        }

        // GET: Location/Delete/5
        public ActionResult Delete(int id = -1)
        {
            var response = _apiHelper.Get(CompileUrl(apiAction), "id", id, GetToken());

            if (response.IsSuccessful)
            {
                var location = JsonConvert.DeserializeObject<LocationViewModel>(response.Content);
                
                return View(location);
            }

            TempData["MessageType"] = "Danger";
            TempData["Message"] = $"There was a problem retrieving this record. Please try again or contact your system administrator.";
            return View();
        }

        // POST: Location/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                
                var response = _apiHelper.Delete(CompileUrl(apiAction), id, GetToken());

                if (response.IsSuccessful)
                {
                    TempData["MessageType"] = "Info";
                    TempData["Message"] = $"Location Deleted";
                    return RedirectToAction("Index");
                }

                TempData["MessageType"] = "Danger";
                TempData["Message"] = $"There was a problem deleting this record. Please try again or contact your system administrator.";
                return View();
            }
            catch
            {
                TempData["MessageType"] = "Danger";
                TempData["Message"] = $"There was a problem deleting this record. Please try again or contact your system administrator.";
                return View();
            }
        }
    }
}

MinistryFunnel.FrontEnd/Views/Location/Create.cshtml
@model MinistryFunnel.FrontEnd.Models.LocationViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Location</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden="hidden">
            @Html.LabelFor(model => model.CreatedDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden="hidden">
            @Html.LabelFor(model => model.ModifiedDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Archived, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList(
                    "Archived", new SelectList(
                            new[]
                            {
                                new { Value = "false", Text = "No" },
                                new { Value = "true", Text = "Yes" },                                
                            }, "Value", "Text", Model
                        )
                    , new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Archived, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MinistryFunnel.FrontEnd/Views/Location/Delete.cshtml
@model MinistryFunnel.FrontEnd.Models.LocationViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

@if (Model != null)
{

    <h3>Are you sure you want to delete this record?</h3>
    <div>
        <h4>Name: @Model.Name</h4>
        <hr />

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Field Name</th>
                    <th scope="col">Field Value</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Name)</td>
                    <td>@Html.DisplayFor(model => model.Name)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.CreatedDateTime)</td>
                    <td>@Html.DisplayFor(model => model.CreatedDateTime)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.ModifiedDateTime)</td>
                    <td>@Html.DisplayFor(model => model.ModifiedDateTime)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Archived)</td>
                    <td>@Html.DisplayFor(model => model.Archived)</td>
                </tr>
            </tbody>
        </table>


    </div>
    <div class="row">
        <div class="col-xs-12">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Confirm Delete" class="btn btn-danger" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
            </div>
            }
        </div>
    </div>
}
else
{
    <h3>This was not a valid ID to edit.</h3>
}

MinistryFunnel.FrontEnd/Views/Location/Details.cshtml
@model MinistryFunnel.FrontEnd.Models.LocationViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Location</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Archived)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Archived)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MinistryFunnel.FrontEnd/Views/Location/Edit.cshtml
@model MinistryFunnel.FrontEnd.Models.LocationViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Location</h2>

@if (Model != null)
{
    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>@Model.Name</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CreatedDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedDateTime, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                    @Html.ValidationMessageFor(model => model.CreatedDateTime, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ModifiedDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ModifiedDateTime, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                    @Html.ValidationMessageFor(model => model.ModifiedDateTime, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Archived, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList(
                    "Archived", new SelectList(
                            new[]
                            {
                                new { Value = "true", Text = "Yes" },
                                new { Value = "false", Text = "No" },
                            }, "Value", "Text", Model
                        )
                    , new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Archived, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
                </div>
            </div>
        </div>
    }
}
else
{
    <h3>This was not a valid ID to edit.</h3>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MinistryFunnel.FrontEnd/Views/Location/Index.cshtml
@model IEnumerable<MinistryFunnel.FrontEnd.Models.LocationViewModel>

@{
    ViewBag.Title = "Location Management Page";
}


<h2>Location Management</h2>

<div class="row">
    <div class="col-sm-12">
        @Html.ActionLink("Create Location", "Create", null, new { @class = "btn btn-success" })
    </div>
</div>
<hr />
<div class="row">
    <div class="col-sm-12">
        @using (Html.BeginForm("Search", "Location", FormMethod.Get))
        {
            <div class="mb-3">
                <label for="searchText" class="form-label">Search by Name</label>
                @Html.TextBox("searchText", null, new { @class = "form-control" })
                <button type="submit" class="btn btn-primary" style="margin-top: 10px;">Search</button>
            </div>
        }
    </div>
</div>

@if (Model != null && Model.Count() > 0)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedDateTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ModifiedDateTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Archived)
                </th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td style="vertical-align: middle;">
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td style="vertical-align: middle;">
                        @Html.DisplayFor(modelItem => item.CreatedDateTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedDateTime)
                    </td>
                    <td style="vertical-align: middle;">
                        @Html.DisplayFor(modelItem => item.Archived)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" })                      
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h3>No records found.</h3>
    @Html.ActionLink("Reload Page", "Index", null, new { @class = "btn btn-secondary" })
}